// Golden test suite — compares Rust embeddings against Python reference outputs.
//
// This test requires:
// 1. A model directory (set via `HYPEMBED_TEST_MODEL_DIR` env var or default `tests/fixtures/model/`)
// 2. A golden reference file (`tests/fixtures/golden.json`) generated by `scripts/generate_golden.py`
//
// The test is `#[ignore]` by default so CI doesn't require model files.
// Run with: `cargo test --test golden_test -- --ignored`

use std::collections::HashMap;

#[test]
#[ignore]
fn test_golden_embeddings() {
    let model_dir = std::env::var("HYPEMBED_TEST_MODEL_DIR")
        .unwrap_or_else(|_| "tests/fixtures/model".to_string());

    let golden_path = std::env::var("HYPEMBED_GOLDEN_PATH")
        .unwrap_or_else(|_| "tests/fixtures/golden.json".to_string());

    // Check model directory exists
    assert!(
        std::path::Path::new(&model_dir).exists(),
        "Model directory not found: {}. Download a model or set HYPEMBED_TEST_MODEL_DIR.",
        model_dir
    );

    // Check golden file exists
    assert!(
        std::path::Path::new(&golden_path).exists(),
        "Golden file not found: {}. Run scripts/generate_golden.py first.",
        golden_path
    );

    // Load model
    let embedder = hypembed::Embedder::load(&model_dir)
        .expect("Failed to load model");

    // Load golden reference
    let golden_json = std::fs::read_to_string(&golden_path)
        .expect("Failed to read golden file");
    let golden: HashMap<String, Vec<Vec<f64>>> = serde_json::from_str(&golden_json)
        .expect("Failed to parse golden JSON");

    let options = hypembed::EmbeddingOptions::default()
        .with_normalize(true)
        .with_pooling(hypembed::PoolingStrategy::Mean)
        .with_max_length(128);

    // Test each sentence
    let tolerance = 1e-4_f64;
    let mut total_tested = 0;
    let mut max_diff: f64 = 0.0;

    for (sentence, expected_embeddings) in &golden {
        let result = embedder
            .embed(&[sentence.as_str()], &options)
            .unwrap_or_else(|e| panic!("Failed to embed '{}': {}", sentence, e));

        assert_eq!(result.len(), 1, "Expected 1 embedding");
        assert_eq!(
            result[0].len(),
            expected_embeddings[0].len(),
            "Embedding dimension mismatch for: {}",
            sentence
        );

        for (i, (&actual, &expected)) in result[0].iter().zip(expected_embeddings[0].iter()).enumerate() {
            let diff = (actual as f64 - expected).abs();
            max_diff = max_diff.max(diff);
            assert!(
                diff < tolerance,
                "Element {} mismatch for '{}': actual={}, expected={}, diff={}",
                i, sentence, actual, expected, diff
            );
        }
        total_tested += 1;
    }

    eprintln!(
        "Golden test passed: {} sentences, max element diff: {:.2e}",
        total_tested, max_diff
    );
}

// Test that the model produces consistent embeddings across multiple runs.
#[test]
#[ignore]
fn test_deterministic_output() {
    let model_dir = std::env::var("HYPEMBED_TEST_MODEL_DIR")
        .unwrap_or_else(|_| "tests/fixtures/model".to_string());

    if !std::path::Path::new(&model_dir).exists() {
        eprintln!("Skipping determinism test: model not found at {}", model_dir);
        return;
    }

    let embedder = hypembed::Embedder::load(&model_dir)
        .expect("Failed to load model");

    let options = hypembed::EmbeddingOptions::default()
        .with_normalize(true)
        .with_pooling(hypembed::PoolingStrategy::Mean);

    let texts = &["Hello world", "Rust is great", "Machine learning"];

    let result1 = embedder.embed(texts, &options).unwrap();
    let result2 = embedder.embed(texts, &options).unwrap();

    for (i, (r1, r2)) in result1.iter().zip(result2.iter()).enumerate() {
        for (j, (&v1, &v2)) in r1.iter().zip(r2.iter()).enumerate() {
            assert_eq!(
                v1, v2,
                "Non-deterministic output at sentence {}, element {}",
                i, j
            );
        }
    }
}
